export const SET_CURRENT_ORDER: 'SET_CURRENT_ORDER'= 'SET_CURRENT_ORDER';
export const CLEAR_CURRENT_ORDER: 'CLEAR_CURRENT_ORDER'= 'CLEAR_CURRENT_ORDER';
export const SET_CURRENT_ORDER_ERROR: 'SET_CURRENT_ORDER_ERROR' = 'SET_CURRENT_ORDER_ERROR';