export const ORDER_LOADING: 'ORDER_LOADING' = 'ORDER_LOADING';
export const ORDER__LOAD_SUCCESS: 'ORDER__LOAD_SUCCESS' = 'ORDER__LOAD_SUCCESS';
export const ORDER_ERROR: 'ORDER_ERROR' = 'ORDER_ERROR';
export const CLEAR_ORDER: 'CLEAR_ORDER' = 'CLEAR_ORDER';