export const CHECK_USER_REGISTRATION: 'CHECK_USER_REGISTRATION' = 'CHECK_USER_REGISTRATION';
export const USER_REG_SUCCESS: 'USER_REG_SUCCESS' = 'USER_REG_SUCCESS';
export const USER_REG_FAILED: 'USER_REG_FAILED' = 'USER_REG_FAILED';

export const CHECK_USER_LOGIN: 'CHECK_USER_LOGIN' = 'CHECK_USER_LOGIN';
export const USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS' = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED: 'USER_LOGIN_FAILED' = 'USER_LOGIN_FAILED';

export const SET_AUTH_CHECKED: 'SET_AUTH_CHECKED' = 'SET_AUTH_CHECKED';
export const GET_USER: 'GET_USER' = 'GET_USER';
export const GET_USER_ERROR: 'GET_USER_ERROR' = 'GET_USER_ERROR';

export const CHEK_USER_LOGOUT: 'CHEK_USER_LOGOUT' = 'CHEK_USER_LOGOUT';
export const USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESST_USER_ERROR' = 'USER_LOGOUT_SUCCESST_USER_ERROR';
export const USER_LOGOUT_ERROR: 'USER_LOGOUT_ERROR' = 'USER_LOGOUT_ERROR';